workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa


    publishing:
      email:
        recipients:
          - nathansanchez745@email.com
