workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS archive
        script: |
          flutter build ios --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your@email.com