workflows:
  ios-release:
    name: iOS Release Build
    environment:
      vars:
        FLUTTER_VERSION: stable
        XCODE_WORKSPACE: Runner.xcworkspace
        XCODE_SCHEME: Runner
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build release for iOS
        script: |
          flutter build ios --release -v
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - your-nathansanchez745@gmail.com
