name: Flutter iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest # Use the macOS runner

    steps:
    - uses: actions/checkout@v4 # Checkout your repository code

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.8.2' # Specify your Flutter version
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: |
        cd ios
        pod install --repo-update # Install iOS dependencies

    - name: Decode Apple Certificate and Provisioning Profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning Profiles/
        echo "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning Profiles/app.mobileprovision

        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
        echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o certificate.p12
        security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "$CERTIFICATE_PASSWORD" -A

    - name: Build iOS IPA
      env:
        EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
      run: |
        echo "$EXPORT_OPTIONS_PLIST" | base64 --decode > ExportOptions.plist
        flutter build ipa --release --export-options-plist=ExportOptions.plist

    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOS-IPA
        path: build/ios/ipa/*.ipa

    - name: Clean up keychain
      if: ${{ always() }}
      run: security delete-keychain build.keychain # Important for security
