name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # allows manual   trigger

jobs:
  build-ios:
    runs-on: macos-latest  # Use the latest macOS version

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.8.2
          channel: stable
          architecture: ARM64
          cache: false
          pub-cache-path: default
          dry-run: false
          git-source: https://github.com/flutter/flutter.git
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release

      - name: Archive build
        run: |
          mkdir -p output
          cp -r build/ios/iphoneos/Runner.app output/

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: output/
