name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # allows manual trigger

jobs:
  build-ios:
    runs-on: macos-latest  # Use the latest macOS version

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.8.1'  # Ensure you're using the correct version
          channel: stable
          architecture: ARM64  # This is correct if you're building for ARM architecture (most modern Macs)
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release

      - name: Archive build
        run: |
          mkdir -p output
          cp -r build/ios/iphoneos/Runner.app output/

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: output/
