name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x' # Adjust to match your project

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release

      - name: Archive build
        run: |
          mkdir -p output
          cp -r build/ios/iphoneos/Runner.app output/

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: output/